{
 "title": "Dashboard Calculadora Examen parcial 2",
 "tags": [
  "calculadora",
  "prometheus",
  "monitoring",
  "devops",
  "loki",
  "examen",
  "cAdvisor"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "RAM usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM en uso",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duración promedio por operación (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(calculadora_operaciones_duracion_ms_sum{tipo=\"suma\"}[5m]) / rate(calculadora_operaciones_duracion_ms_count{tipo=\"suma\"}[5m])",
     "legendFormat": "Suma (ms)"
    },
    {
     "expr": "rate(calculadora_operaciones_duracion_ms_sum{tipo=\"resta\"}[5m]) / rate(calculadora_operaciones_duracion_ms_count{tipo=\"resta\"}[5m])",
     "legendFormat": "Resta (ms)"
    },
    {
     "expr": "rate(calculadora_operaciones_duracion_ms_sum{tipo=\"multiplicacion\"}[5m]) / rate(calculadora_operaciones_duracion_ms_count{tipo=\"multiplicacion\"}[5m])",
     "legendFormat": "Multiplicación (ms)"
    },
    {
     "expr": "rate(calculadora_operaciones_duracion_ms_sum{tipo=\"division\"}[5m]) / rate(calculadora_operaciones_duracion_ms_count{tipo=\"division\"}[5m])",
     "legendFormat": "División (ms)"
    }
   ]
  },
  {
   "title": "Errores por operación",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(calculadora_operaciones_error_total{tipo=\"suma\"}[5m])",
     "legendFormat": "Errores Suma"
    },
    {
     "expr": "increase(calculadora_operaciones_error_total{tipo=\"resta\"}[5m])",
     "legendFormat": "Errores Resta"
    },
    {
     "expr": "increase(calculadora_operaciones_error_total{tipo=\"multiplicacion\"}[5m])",
     "legendFormat": "Errores Multiplicación"
    },
    {
     "expr": "increase(calculadora_operaciones_error_total{tipo=\"division\"}[5m])",
     "legendFormat": "Errores División"
    }
   ]
  },
  {
   "title": "Porcentaje de errores SUMA (%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum(calculadora_operaciones_error_total{tipo=\"suma\"}) \r\n  /\r\n  (sum(calculadora_operaciones_total{tipo=\"suma\"}) + 1)\r\n)\r\n",
     "legendFormat": "Suma %"
    }
   ]
  },
  {
   "title": "Porcentaje de errores RESTA (%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum(calculadora_operaciones_error_total{tipo=\"resta\"}) \r\n  /\r\n  (sum(calculadora_operaciones_total{tipo=\"resta\"}) + 1)\r\n)\r\n",
     "legendFormat": "Resta %"
    }
   ]
  },
  {
   "title": "Porcentaje de errores MULTIPLICACIÓN (%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum(calculadora_operaciones_error_total{tipo=\"multiplicacion\"}) \r\n  /\r\n  (sum(calculadora_operaciones_total{tipo=\"multiplicacion\"}) + 1)\r\n)\r\n",
     "legendFormat": "Multiplicación %"
    }
   ]
  },
  {
   "title": "Porcentaje de errores DIVISIÓN (%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum(calculadora_operaciones_error_total{tipo=\"division\"}) \r\n  /\r\n  (sum(calculadora_operaciones_total{tipo=\"division\"}) + 1)\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cantidad de operaciones por tipo",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "increase(calculadora_operaciones_total{tipo=\"suma\"}[5m])",
     "legendFormat": "Suma"
    },
    {
     "expr": "increase(calculadora_operaciones_total{tipo=\"resta\"}[5m])",
     "legendFormat": "Resta"
    },
    {
     "expr": "increase(calculadora_operaciones_total{tipo=\"multiplicacion\"}[5m])",
     "legendFormat": "Multiplicación"
    },
    {
     "expr": "increase(calculadora_operaciones_total{tipo=\"division\"}[5m])",
     "legendFormat": "División"
    }
   ]
  },
  {
   "title": "Logs General",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"FastApi\"}"
    }
   ]
  },
  {
   "title": "Logs Informativos General",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"FastApi\"} |= \"INFO\"\r\n"
    }
   ]
  },
  {
   "title": "Logs Errores General",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"FastApi\"} |= \"ERROR\"\r\n"
    }
   ]
  },
  {
   "title": "Logs Endpoint SUMA",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"FastApi\"} |= \"sumar\"\r\n"
    }
   ]
  },
  {
   "title": "Logs Endpoint RESTAR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"FastApi\"} |= \"restar\"\r\n"
    }
   ]
  },
  {
   "title": "Logs Endpoint MULTIPLICAR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"FastApi\"} |= \"multiplicar\""
    }
   ]
  },
  {
   "title": "Logs Endpoint DIVIDIR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"FastApi\"} |= \"division\""
    }
   ]
  },
  {
   "title": "Logs MongoDB",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"FastApi\"} |= \"Mongo\"\r\n"
    }
   ]
  }
 ]
}